### ISSUE TITLE
When Queue is empty, then method fetchMessage is throws exception.

### ISSUE THREAD

**Issue by tkuldeep** [lelivrescolaire/SQSBundle#4]
When Queue is empty, and still someone tries to fetch Message from queue, then method `fetchMessages()` of `Queue.php` throws error.
```[Symfony\Component\Debug\Exception\ContextErrorException]  Warning: array_map(): Argument #2 should be an array```
 
We should add check here, I will create PR for it.

**Comment by tkuldeep** [comment]
Thanks @JJK801 for merging my PR.

**Comment by JJK801** [comment]
@tkuldeep my pleasure, thanks for this contribution.
