### ISSUE TITLE
QueueFactory is not set automatically to SQS service.

### ISSUE THREAD

**Issue by tkuldeep** [lelivrescolaire/SQSBundle#8]
When I invoke method `getQueue` of SQS service, it says ` Call to a member function create() on a non-object` as `queueFactory` has not been set to SQS service. So I had to set it manually by following code.
``` $sqsAsService = $this->container->get('llsaws.services.synpost_sqs_service');
        $sqsAsService->setQueueFactory($qeueFactory);```

Now my doubt why I should set it's dependency `QueueFactoryInterface` manually in SQS serivce. Should it not be set automatically. 
Please forgive it my doubt is silly.

**Comment by Nainterceptor** [comment]
Thanks @tkuldeep, you saved my time.
If it's the wanted behavior, maybe we can add this snippet to README.md ?

**Comment by JJK801** [comment]
My bad, QueueFactory must be added at service call automatically but it seems it missed a sample of code to do that in [AWSBundle](https://github.com/lelivrescolaire/AWSBundle/blob/master/Factory/GenericServiceFactory.php#L35) (arguments are keeped but not used). I will fix it soon. Thx @tkuldeep @Nainterceptor

**Comment by JJK801** [comment]
@tkuldeep @Nainterceptor The [last commit](https://github.com/lelivrescolaire/SQSBundle/commit/a955c55dc8bbcc988b51d1c06ad507095a440bc3) will fix this, can you confirm it ?

**Comment by Nainterceptor** [comment]
@JJK801 Seems to be OK here, setQueueFactory has been removed and it's working. Thanks !

**Comment by JJK801** [comment]
Thanks guys :)
